/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import CheckOutlineImage from 'src/assets/images/Checkmark_check_outline.png';
import CheckedImage from 'src/assets/images/Checkmark_checked.png';
import { styled } from '@mui/material/styles';

const CheckNotChecked = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const CheckOutline = styled('img')({
  height: `28px`,
  width: `28px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Checked = styled('img')({
  height: `28px`,
  width: `28px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function CheckMark(props) {
  return (
    <CheckNotChecked>
      <Helmet>
        <title>Check mark</title>
      </Helmet>
      <CheckOutline
        src={CheckOutlineImage}
        loading="lazy"
        alt={'check_outline'}
      />
      {false && <Checked src={CheckedImage} loading="lazy" alt={'checked'} />}
    </CheckNotChecked>
  );
}

export default CheckMark;
