/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Link } from '@mui/material';
import XOutImage from 'src/assets/images/Steps_X_out.png';
import Step1ImageryImage from 'src/assets/images/Steps_Step1_imagery.png';
import Step2ImageryImage from 'src/assets/images/Steps_Step2_imagery.png';
import Step3ImageryImage from 'src/assets/images/Steps_Step3_imagery.png';
import Step4ImageryImage from 'src/assets/images/Steps_Step4_imagery.png';
import { styled } from '@mui/material/styles';
import CheckMark from 'src/components/CheckMark/CheckMark';

const Steps1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: '100%',
});

const Banner = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Row = styled('div')({
  background: `linear-gradient(90deg, rgba(56, 183, 255, 1) 2.038461443163306%, rgba(138, 136, 255, 1) 97.23076989926574%)`,
  border: `1px solid rgba(138, 136, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `10px 20px`,
  flexGrow: `1`,
  margin: `0px`,
});

const ThanksTxt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const Thanks = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const YourAccountIsNowSetu = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `500`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `none`,
  margin: `0px 0px 0px 28px`,
});

const XOut = styled('img')({
  height: `16px`,
  width: `16px`,
  margin: `0px 0px 0px 30px`,
});

const Steps2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const TopTxt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 14px 0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const QuickStartGuide = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `1300px`,
  margin: `0px`,
});

const FollowTheseStepsToBu = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `1300px`,
  margin: `4px 0px 0px 0px`,
});

const Content = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `8px 0px 0px 0px`,
});

const LeftSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `572px`,
  margin: `0px`,
});

const QuickStart = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `572px`,
  margin: `0px`,
});

const Checklist = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `572px`,
  margin: `0px`,
});

const Checklist1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `572px`,
  margin: `0px`,
});

const OnboardingRow = styled('div')({
  background: `linear-gradient(90deg, rgba(233, 242, 255, 0.9) -0.00000875349733583611%, rgba(237, 237, 255, 0.9) 95.79438761196948%)`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Content1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const CheckMark1 = styled(CheckMark)(({ theme }) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px`,
}));

const Txt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9.402298927307129px`,
});

const Q1GetThisFigmaFile = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `27px`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtxt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  margin: `2px 0px 0px 0px`,
});

const OpenThe = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Link1 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `0px 0px 0px 4px`,
}));

const FigmaFile = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 4px`,
});

const Border = styled('div')({
  backgroundColor: `rgba(237, 237, 237, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `1.57px`,
  margin: `0px`,
});

const OnboardingRow1 = styled('div')({
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Content2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const CheckMark2 = styled(CheckMark)(({ theme }) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px`,
}));

const Txt1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9.402298927307129px`,
});

const Q2ExportYourComponen = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `27px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame37 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `2px 0px 0px 0px`,
});

const Subtxt1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const SelectCardItemFromTh = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtxt2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  margin: `1px 0px 0px 0px`,
});

const ExportUsingThe = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Link2 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `0px 0px 0px 4px`,
}));

const Border1 = styled('div')({
  backgroundColor: `rgba(237, 237, 237, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `1.57px`,
  margin: `0px`,
});

const OnboardingRow2 = styled('div')({
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Content3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const CheckMark3 = styled(CheckMark)(({ theme }) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px`,
}));

const Txt2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9.402298927307129px`,
});

const Q3SetupPropsBindings = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `27px`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtxt3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  width: `468px`,
  margin: `2px 0px 0px 0px`,
});

const OpenTheComponentInYo = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `466px`,
  margin: `0px`,
});

const Border2 = styled('div')({
  backgroundColor: `rgba(237, 237, 237, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `1.57px`,
  margin: `0px`,
});

const OnboardingRow3 = styled('div')({
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Border3 = styled('div')({
  backgroundColor: `rgba(237, 237, 237, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `1.57px`,
  margin: `0px`,
});

const Content4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const CheckMark4 = styled(CheckMark)(({ theme }) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px`,
}));

const Txt3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9.402298927307129px`,
});

const Q4PreviewDownloadCod = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `27px`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtxt4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  margin: `2px 0px 0px 0px`,
});

const PreviewTheComponentU = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `365px`,
  margin: `0px`,
});

const RightSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 60px`,
});

const Step1Imagery = styled('img')({
  height: `506px`,
  width: `450px`,
  margin: `0px`,
});

const Step2Imagery = styled('img')({
  height: `506px`,
  width: `450px`,
  margin: `0px 0px 0px 10px`,
});

const Step3Imagery = styled('img')({
  height: `506px`,
  width: `450px`,
  margin: `0px 0px 0px 10px`,
});

const Step4Imagery = styled('img')({
  height: `506px`,
  width: `450px`,
  margin: `0px 0px 0px 10px`,
});

function Steps(props) {
  return (
    <Steps1>
      <Banner>
        <Row>
          <ThanksTxt>
            <Thanks>{`Thanks!`}</Thanks>
            <YourAccountIsNowSetu>
              {`Your Account is now setup with Next.js as the export type & Typescript as the file type. `}
            </YourAccountIsNowSetu>
          </ThanksTxt>
          {false && <XOut src={XOutImage} loading="lazy" alt={'X out'} />}
        </Row>
      </Banner>
      <Steps2>
        <TopTxt>
          <QuickStartGuide>{`Quick Start Guide`}</QuickStartGuide>
          <FollowTheseStepsToBu>
            {`Follow these steps to build your first component.`}
          </FollowTheseStepsToBu>
        </TopTxt>
        <Content>
          <LeftSide>
            <QuickStart>
              <Checklist>
                <Checklist1>
                  <OnboardingRow>
                    <Content1>
                      <CheckMark1 />
                      <Txt>
                        <Q1GetThisFigmaFile>
                          {`1. Get this Figma file`}
                        </Q1GetThisFigmaFile>
                        <Subtxt>
                          <OpenThe>{`Open the`}</OpenThe>
                          <Link1 href="#" underline="hover">
                            Quest Component Templates
                          </Link1>
                          <FigmaFile>{`Figma file`}</FigmaFile>
                        </Subtxt>
                      </Txt>
                    </Content1>
                    {false && <Border></Border>}
                  </OnboardingRow>
                  <OnboardingRow1>
                    <Content2>
                      <CheckMark2 />
                      <Txt1>
                        <Q2ExportYourComponen>
                          {`2. Export your Component from Figma`}
                        </Q2ExportYourComponen>
                        <Frame37>
                          <Subtxt1>
                            <SelectCardItemFromTh>
                              {`Select “Card” item from the list of Pages and select “Card-2” frame. `}
                            </SelectCardItemFromTh>
                          </Subtxt1>
                          <Subtxt2>
                            <ExportUsingThe>
                              {`Export using the`}
                            </ExportUsingThe>
                            <Link2 href="#" underline="hover">
                              Quest Figma plugin.
                            </Link2>
                          </Subtxt2>
                        </Frame37>
                      </Txt1>
                    </Content2>
                    {false && <Border1></Border1>}
                  </OnboardingRow1>
                  <OnboardingRow2>
                    <Content3>
                      <CheckMark3 />
                      <Txt2>
                        <Q3SetupPropsBindings>
                          {`3. Setup Props & Bindings`}
                        </Q3SetupPropsBindings>
                        <Subtxt3>
                          <OpenTheComponentInYo>
                            {`Open the component in your Quest account. With “Component” 
selected in the left panel, add a new prop on the right panel as shown ->
Then select “property title” layer on the left and add a new binding as shown ->`}
                          </OpenTheComponentInYo>
                        </Subtxt3>
                      </Txt2>
                    </Content3>
                    {false && <Border2></Border2>}
                  </OnboardingRow2>
                  <OnboardingRow3>
                    {false && <Border3></Border3>}
                    <Content4>
                      <CheckMark4 />
                      <Txt3>
                        <Q4PreviewDownloadCod>
                          {`4. Preview & Download code`}
                        </Q4PreviewDownloadCod>
                        <Subtxt4>
                          <PreviewTheComponentU>
                            {`Preview the component using the Preview button. Download the ReactJS component code and view it in your code editor.`}
                          </PreviewTheComponentU>
                        </Subtxt4>
                      </Txt3>
                    </Content4>
                  </OnboardingRow3>
                </Checklist1>
              </Checklist>
            </QuickStart>
          </LeftSide>
          <RightSide>
            <Step1Imagery
              src={Step1ImageryImage}
              loading="lazy"
              alt={'Step1_imagery'}
            />
            {false && (
              <Step2Imagery
                src={Step2ImageryImage}
                loading="lazy"
                alt={'Step2_imagery'}
              />
            )}
            {false && (
              <Step3Imagery
                src={Step3ImageryImage}
                loading="lazy"
                alt={'Step3_imagery'}
              />
            )}
            {false && (
              <Step4Imagery
                src={Step4ImageryImage}
                loading="lazy"
                alt={'Step4_imagery'}
              />
            )}
          </RightSide>
        </Content>
      </Steps2>
    </Steps1>
  );
}

export default Steps;
