/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import {
  Button,
  FormControl,
  RadioGroup,
  Radio,
  FormControlLabel,
  Link,
} from '@mui/material';
import QuestDashboardLogoImage from 'src/assets/images/Dashboard_Quest_dashboard_logo.png';
import XOutImage from 'src/assets/images/Dashboard_X_out_1.png';
import Step1ImageryImage from 'src/assets/images/Dashboard_Step1_imagery.png';
import Step2ImageryImage from 'src/assets/images/Dashboard_Step2_imagery.png';
import Step3ImageryImage from 'src/assets/images/Dashboard_Step3_imagery.png';
import Step4ImageryImage from 'src/assets/images/Dashboard_Step4_imagery.png';
import XOut1Image from 'src/assets/images/Dashboard_X_out.png';
import DashIconMuiImage from 'src/assets/images/Dashboard_dash_icon_MUI.png';
import IconDashReactImage from 'src/assets/images/Dashboard_icon_dash_react.png';
import IconDashExportImage from 'src/assets/images/Dashboard_icon_dash_export.png';
import IconDashZoomImage from 'src/assets/images/Dashboard_icon_dash_zoom_1.png';
import IconDashZoom1Image from 'src/assets/images/Dashboard_icon_dash_zoom.png';
import { styled } from '@mui/material/styles';
import CheckMark from 'src/components/CheckMark/CheckMark';

const Dashboard1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: '100%',
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `34px 50px`,
  boxSizing: `border-box`,
});

const Questions = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Avatar1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 34px`,
});

const Avatar2 = styled('div')({
  backgroundColor: `rgba(205, 204, 255, 1)`,
  borderRadius: `360px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `150px`,
  width: `150px`,
  margin: `0px`,
});

const A = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `300`,
  fontSize: `98px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Name = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `14px 0px 0px 0px`,
});

const Andrew = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const ButtonText = styled(Button)({
  margin: `14px 0px 0px 0px`,
});

const WelcomeQuiz = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `30px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const Top = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const TopSec = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Top1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Welcome = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const WelcomeTo = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `26px`,
  letterSpacing: `-0.26px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `359px`,
  margin: `0px`,
});

const QuestDashboardLogo = styled('img')({
  height: `56px`,
  width: `226px`,
  objectFit: `contain`,
  margin: `10px 0px 0px 0px`,
});

const HelpUsCustomizeYourE = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `none`,
  width: `333px`,
  margin: `58px 0px 0px 0px`,
});

const Divider = styled('div')({
  backgroundColor: `rgba(218, 218, 218, 1)`,
  alignSelf: `stretch`,
  height: `1px`,
  margin: `28px 0px 0px 0px`,
});

const Q1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px 0px`,
  boxSizing: `border-box`,
  margin: `22px 0px 0px 0px`,
});

const WhatAreYouBuilding = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `333px`,
  margin: `0px`,
});

const OptionsAndReason = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `18px 0px 0px 0px`,
});

const Options1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const FormControlLabel1 = styled(FormControlLabel)({
  margin: `0px`,
});

const FormControlLabel2 = styled(FormControlLabel)({
  margin: `4px 0px 0px 0px`,
});

const FormControlLabel3 = styled(FormControlLabel)({
  margin: `4px 0px 0px 0px`,
});

const Botom = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 0px 10px`,
  boxSizing: `border-box`,
  width: `1056px`,
  margin: `18px 0px 0px 0px`,
});

const SubmitCancel = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `4px 10px 0px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ButtonContained = styled(Button)({
  margin: `0px`,
});

const Q2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px 0px`,
  boxSizing: `border-box`,
  margin: `22px 0px 0px 0px`,
});

const WhatIsYourPreferredL = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `333px`,
  margin: `0px`,
});

const OptionsAndReason1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `18px 0px 0px 0px`,
});

const Options2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const FormControlLabel4 = styled(FormControlLabel)({
  margin: `0px`,
});

const FormControlLabel5 = styled(FormControlLabel)({
  margin: `4px 0px 0px 0px`,
});

const Botom1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 0px 10px`,
  boxSizing: `border-box`,
  width: `1056px`,
  margin: `18px 0px 0px 0px`,
});

const SubmitCancel1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `4px 10px 0px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ButtonContained1 = styled(Button)({
  margin: `0px`,
});

const Q3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px 0px`,
  boxSizing: `border-box`,
  margin: `22px 0px 0px 0px`,
});

const WhoAreYou = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `333px`,
  margin: `0px`,
});

const OptionsAndReason2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `18px 0px 0px 0px`,
});

const Options3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const FormControlLabel6 = styled(FormControlLabel)({
  margin: `0px`,
});

const FormControlLabel7 = styled(FormControlLabel)({
  margin: `4px 0px 0px 0px`,
});

const FormControlLabel8 = styled(FormControlLabel)({
  margin: `4px 0px 0px 0px`,
});

const FormControlLabel9 = styled(FormControlLabel)({
  margin: `4px 0px 0px 0px`,
});

const Botom2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 0px 10px`,
  boxSizing: `border-box`,
  width: `1056px`,
  margin: `18px 0px 0px 0px`,
});

const SubmitCancel2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `4px 10px 0px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ButtonContained2 = styled(Button)({
  margin: `0px`,
});

const Steps = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `10px 0px 0px 0px`,
});

const Banner = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Row = styled('div')({
  background: `linear-gradient(90deg, rgba(56, 183, 255, 1) 2.038461443163306%, rgba(138, 136, 255, 1) 97.23076989926574%)`,
  border: `1px solid rgba(138, 136, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `10px 20px`,
  flexGrow: `1`,
  margin: `0px`,
});

const ThanksTxt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const Thanks = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const YourAccountIsNowSetu = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `500`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `none`,
  margin: `0px 0px 0px 28px`,
});

const XOut = styled('img')({
  height: `16px`,
  width: `16px`,
  margin: `0px 0px 0px 30px`,
});

const Steps1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const TopTxt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 0px 14px 0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const QuickStartGuide = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `1300px`,
  margin: `0px`,
});

const FollowTheseStepsToBu = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `500`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `1300px`,
  margin: `4px 0px 0px 0px`,
});

const Content = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `8px 0px 0px 0px`,
});

const LeftSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `572px`,
  margin: `0px`,
});

const QuickStart = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `572px`,
  margin: `0px`,
});

const Checklist = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `572px`,
  margin: `0px`,
});

const Checklist1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `572px`,
  margin: `0px`,
});

const OnboardingRow = styled('div')({
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Content1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const CheckMark1 = styled(CheckMark)(({ theme }) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px`,
}));

const Txt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9.402298927307129px`,
});

const Q1GetThisFigmaFile = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `27px`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtxt = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  margin: `2px 0px 0px 0px`,
});

const OpenThe = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Link1 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `0px 0px 0px 4px`,
}));

const FigmaFile = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 4px`,
});

const Border = styled('div')({
  backgroundColor: `rgba(237, 237, 237, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `1.57px`,
  margin: `0px`,
});

const OnboardingRow1 = styled('div')({
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Content2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const CheckMark2 = styled(CheckMark)(({ theme }) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px`,
}));

const Txt1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9.402298927307129px`,
});

const Q2ExportYourComponen = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `27px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame37 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `2px 0px 0px 0px`,
});

const Subtxt1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const SelectCardItemFromTh = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtxt2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  margin: `1px 0px 0px 0px`,
});

const ExportUsingThe = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Link2 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `0px 0px 0px 4px`,
}));

const Border1 = styled('div')({
  backgroundColor: `rgba(237, 237, 237, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `1.57px`,
  margin: `0px`,
});

const OnboardingRow2 = styled('div')({
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Content3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const CheckMark3 = styled(CheckMark)(({ theme }) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px`,
}));

const Txt2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9.402298927307129px`,
});

const Q3SetupPropsBindings = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `27px`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtxt3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  width: `468px`,
  margin: `2px 0px 0px 0px`,
});

const OpenTheComponentInYo = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `466px`,
  margin: `0px`,
});

const Border2 = styled('div')({
  backgroundColor: `rgba(237, 237, 237, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `1.57px`,
  margin: `0px`,
});

const OnboardingRow3 = styled('div')({
  background: `linear-gradient(90deg, rgba(233, 242, 255, 0.9) -0.000010555687963802369%, rgba(237, 237, 255, 0.9) 95.79438580977886%)`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Border3 = styled('div')({
  backgroundColor: `rgba(237, 237, 237, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `1.57px`,
  margin: `0px`,
});

const Content4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 20px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const CheckMark4 = styled(CheckMark)(({ theme }) => ({
  width: `28px`,
  height: `28px`,
  margin: `0px`,
}));

const Txt3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 9.402298927307129px`,
});

const Q4PreviewDownloadCod = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `-0.36px`,
  textDecoration: `none`,
  lineHeight: `27px`,
  textTransform: `none`,
  margin: `0px`,
});

const Subtxt4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 2px`,
  boxSizing: `border-box`,
  margin: `2px 0px 0px 0px`,
});

const PreviewTheComponentU = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `-0.28px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `365px`,
  margin: `0px`,
});

const RightSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 60px`,
});

const Step1Imagery = styled('img')({
  height: `506px`,
  width: `450px`,
  margin: `0px 0px 0px 10px`,
});

const Step2Imagery = styled('img')({
  height: `506px`,
  width: `450px`,
  margin: `0px 0px 0px 10px`,
});

const Step3Imagery = styled('img')({
  height: `506px`,
  width: `450px`,
  margin: `0px 0px 0px 10px`,
});

const Step4Imagery = styled('img')({
  height: `506px`,
  width: `450px`,
  margin: `0px`,
});

const Resources = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `40px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `10px 0px 0px 0px`,
});

const Banner1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const Row1 = styled('div')({
  border: `1px solid rgba(138, 136, 255, 1)`,
  boxSizing: `border-box`,
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `10px 20px`,
  flexGrow: `1`,
  margin: `0px`,
});

const ThanksTxt1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const Thanks1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const YourAccountIsNowSetu1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `none`,
  margin: `0px 0px 0px 22px`,
});

const XOut1 = styled('img')({
  height: `16px`,
  width: `16px`,
  margin: `0px 0px 0px 30px`,
});

const Thanks2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Top2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `18px 0px 0px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: `290px`,
  margin: `0px`,
});

const Avatar3 = styled('div')({
  backgroundColor: `rgba(205, 204, 255, 1)`,
  borderRadius: `360px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `150px`,
  width: `150px`,
  margin: `0px`,
});

const A1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(39, 39, 39, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `300`,
  fontSize: `98px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Name1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `14px 0px 0px 0px`,
});

const Andrew1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const ButtonText1 = styled(Button)({
  margin: `14px 0px 0px 0px`,
});

const ResourceBoxes = styled('div')({
  backgroundColor: `rgba(253, 253, 253, 1)`,
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px 0px 0px 30px`,
});

const Title = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 30px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px 0px 0px 50px`,
});

const IconAndTitle = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Resources1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `271px`,
  margin: `0px`,
});

const Row2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px 10px 10px 0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const Resource = styled('div')({
  backgroundColor: `rgba(253, 253, 253, 1)`,
  boxShadow: `0px 9px 18px rgba(0, 0, 0, 0.06)`,
  border: `1px solid rgba(206, 206, 206, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px 0px`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Top3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 22px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const IconAndTitle1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const DashIconMui = styled('img')({
  height: `70px`,
  width: `70px`,
  margin: `0px`,
});

const Description = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 30px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const OverviewVideo = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  margin: `0px`,
});

const Resource1 = styled('div')({
  backgroundColor: `rgba(253, 253, 253, 1)`,
  boxShadow: `0px 9px 18px rgba(0, 0, 0, 0.06)`,
  border: `1px solid rgba(206, 206, 206, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px 0px`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

const Top4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 22px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const IconAndTitle2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IconDashReact = styled('img')({
  height: `70px`,
  width: `70px`,
  margin: `0px`,
});

const Description1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 30px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const QuickStartDoc = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  margin: `0px`,
});

const Resource2 = styled('div')({
  backgroundColor: `rgba(253, 253, 253, 1)`,
  boxShadow: `0px 9px 18px rgba(0, 0, 0, 0.06)`,
  border: `1px solid rgba(206, 206, 206, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px 0px`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

const Top5 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 22px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const IconAndTitle3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IconDashExport = styled('img')({
  height: `70px`,
  width: `70px`,
  margin: `0px`,
});

const Description2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 30px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const GetTheFigmaPlugin = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  margin: `0px`,
});

const Resource3 = styled('div')({
  backgroundColor: `rgba(253, 253, 253, 1)`,
  boxShadow: `0px 9px 18px rgba(0, 0, 0, 0.06)`,
  border: `1px solid rgba(206, 206, 206, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px 0px`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

const Top6 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 22px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const IconAndTitle4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IconDashZoom = styled('img')({
  height: `70px`,
  width: `70px`,
  margin: `0px`,
});

const Description3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 30px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const JoinUsOnDiscord = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  margin: `0px`,
});

const Resource4 = styled('div')({
  backgroundColor: `rgba(253, 253, 253, 1)`,
  boxShadow: `0px 9px 18px rgba(0, 0, 0, 0.06)`,
  border: `1px solid rgba(206, 206, 206, 1)`,
  boxSizing: `border-box`,
  borderRadius: `12px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px 0px`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
});

const Top7 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px 22px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const IconAndTitle5 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IconDashZoom1 = styled('img')({
  height: `70px`,
  width: `70px`,
  margin: `0px`,
});

const Description4 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 30px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  margin: `0px`,
});

const ScheduleDemoOnboardi = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  margin: `0px`,
});

const Links = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px 0px 0px 0px`,
  boxSizing: `border-box`,
  flexGrow: `1`,
  height: `577px`,
  margin: `0px 0px 0px 50px`,
});

const IconAndTitle6 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px 0px 0px 20px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Links1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(58, 58, 58, 1)`,
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `none`,
  width: `271px`,
  margin: `0px`,
});

const Link3 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `14px 0px 0px 0px`,
}));

const Link4 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `14px 0px 0px 0px`,
}));

const Link5 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `14px 0px 0px 0px`,
}));

const Link6 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `14px 0px 0px 0px`,
}));

const Link7 = styled(Link)(({ theme }) => ({
  color: theme.palette['Primary']['Main'],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textTransform: `none`,
  margin: `14px 0px 0px 0px`,
}));

const Resources2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  alignSelf: `stretch`,
  height: `211px`,
  margin: `40px 0px 0px 0px`,
});

function Dashboard(props) {
  return (
    <Dashboard1>
      <Questions>
        {false && (
          <Avatar1>
            <Avatar2>
              <A>{`A`}</A>
            </Avatar2>
            <Name>
              <Andrew>{`Andrew`}</Andrew>
            </Name>
            {false && (
              <ButtonText variant="text" size="medium" color="primary">
                {' '}
                Edit Profile{' '}
              </ButtonText>
            )}
          </Avatar1>
        )}
        <WelcomeQuiz>
          <Top>
            <TopSec>
              <Top1>
                <Welcome>
                  <WelcomeTo>{`Welcome to`}</WelcomeTo>
                  <QuestDashboardLogo
                    src={QuestDashboardLogoImage}
                    loading="lazy"
                    alt={'Quest dashboard logo'}
                  />
                </Welcome>
                <HelpUsCustomizeYourE>
                  {`Help us customize your experience and get you started in the right direction.`}
                </HelpUsCustomizeYourE>
              </Top1>
              <Divider></Divider>
            </TopSec>
          </Top>
          <Q1>
            <WhatAreYouBuilding>{`What are you building?`}</WhatAreYouBuilding>
            <OptionsAndReason>
              <Options1>
                <FormControl>
                  <RadioGroup
                    id={'what_are_you_building'}
                    name={'what_are_you_building'}
                    aria-label={'what_are_you_building'}
                  >
                    <FormControlLabel1
                      control={<Radio color="primary" size="medium" />}
                      label={'A new ReactJS App'}
                    />
                    <FormControlLabel2
                      control={<Radio color="primary" size="medium" />}
                      label={'A ReactJS component for an existing App'}
                    />
                    <FormControlLabel3
                      control={<Radio color="primary" size="medium" />}
                      label={'A website using NextJS'}
                    />
                  </RadioGroup>
                </FormControl>
              </Options1>
            </OptionsAndReason>
            <Botom>
              <SubmitCancel>
                <ButtonContained
                  variant="contained"
                  size="medium"
                  color="primary"
                >
                  {' '}
                  Next Question >{' '}
                </ButtonContained>
              </SubmitCancel>
            </Botom>
          </Q1>
          {false && (
            <Q2>
              <WhatIsYourPreferredL>
                {`What is your preferred language?`}
              </WhatIsYourPreferredL>
              <OptionsAndReason1>
                <Options2>
                  <FormControlLabel4
                    control={<Radio color="primary" size="medium" />}
                    label={'Javascript'}
                  />
                  <FormControlLabel5
                    control={<Radio color="primary" size="medium" />}
                    label={'Typescript'}
                  />
                </Options2>
              </OptionsAndReason1>
              <Botom1>
                <SubmitCancel1>
                  <ButtonContained1
                    variant="contained"
                    size="medium"
                    color="primary"
                  >
                    {' '}
                    Last Question >{' '}
                  </ButtonContained1>
                </SubmitCancel1>
              </Botom1>
            </Q2>
          )}
          {false && (
            <Q3>
              <WhoAreYou>{`Who are you?`}</WhoAreYou>
              <OptionsAndReason2>
                <Options3>
                  <FormControlLabel6
                    control={<Radio color="primary" size="medium" />}
                    label={'Startup'}
                  />
                  <FormControlLabel7
                    control={<Radio color="primary" size="medium" />}
                    label={'Product Development team in a company'}
                  />
                  <FormControlLabel8
                    control={<Radio color="primary" size="medium" />}
                    label={'Agency building for my clients'}
                  />
                  <FormControlLabel9
                    control={<Radio color="primary" size="medium" />}
                    label={'Student or Educator'}
                  />
                </Options3>
              </OptionsAndReason2>
              <Botom2>
                <SubmitCancel2>
                  <ButtonContained2
                    variant="contained"
                    size="medium"
                    color="primary"
                  >
                    {' '}
                    Finish Setup >{' '}
                  </ButtonContained2>
                </SubmitCancel2>
              </Botom2>
            </Q3>
          )}
        </WelcomeQuiz>
      </Questions>
      {false && (
        <Steps>
          <Banner>
            <Row>
              <ThanksTxt>
                <Thanks>{`Thanks!`}</Thanks>
                <YourAccountIsNowSetu>
                  {`Your Account is now setup with Next.js as the export type & Typescript as the file type. `}
                </YourAccountIsNowSetu>
              </ThanksTxt>
              {false && <XOut src={XOutImage} loading="lazy" alt={'X out'} />}
            </Row>
          </Banner>
          <Steps1>
            <TopTxt>
              <QuickStartGuide>{`Quick Start Guide`}</QuickStartGuide>
              <FollowTheseStepsToBu>
                {`Follow these steps to build your first component.`}
              </FollowTheseStepsToBu>
            </TopTxt>
            <Content>
              <LeftSide>
                <QuickStart>
                  <Checklist>
                    <Checklist1>
                      <OnboardingRow>
                        <Content1>
                          <CheckMark1 />
                          <Txt>
                            <Q1GetThisFigmaFile>
                              {`1. Get this Figma file`}
                            </Q1GetThisFigmaFile>
                            <Subtxt>
                              <OpenThe>{`Open the`}</OpenThe>
                              <Link1 href="#" underline="hover">
                                Quest Component Templates
                              </Link1>
                              <FigmaFile>{`Figma file`}</FigmaFile>
                            </Subtxt>
                          </Txt>
                        </Content1>
                        {false && <Border></Border>}
                      </OnboardingRow>
                      <OnboardingRow1>
                        <Content2>
                          <CheckMark2 />
                          <Txt1>
                            <Q2ExportYourComponen>
                              {`2. Export your Component from Figma`}
                            </Q2ExportYourComponen>
                            <Frame37>
                              <Subtxt1>
                                <SelectCardItemFromTh>
                                  {`Select “Card” item from the list of Pages and select “Card-2” frame. `}
                                </SelectCardItemFromTh>
                              </Subtxt1>
                              <Subtxt2>
                                <ExportUsingThe>
                                  {`Export using the`}
                                </ExportUsingThe>
                                <Link2 href="#" underline="hover">
                                  Quest Figma plugin.
                                </Link2>
                              </Subtxt2>
                            </Frame37>
                          </Txt1>
                        </Content2>
                        {false && <Border1></Border1>}
                      </OnboardingRow1>
                      <OnboardingRow2>
                        <Content3>
                          <CheckMark3 />
                          <Txt2>
                            <Q3SetupPropsBindings>
                              {`3. Setup Props & Bindings`}
                            </Q3SetupPropsBindings>
                            <Subtxt3>
                              <OpenTheComponentInYo>
                                {`Open the component in your Quest account. With “Component” 
selected in the left panel, add a new prop on the right panel as shown ->
Then select “property title” layer on the left and add a new binding as shown ->`}
                              </OpenTheComponentInYo>
                            </Subtxt3>
                          </Txt2>
                        </Content3>
                        {false && <Border2></Border2>}
                      </OnboardingRow2>
                      <OnboardingRow3>
                        {false && <Border3></Border3>}
                        <Content4>
                          <CheckMark4 />
                          <Txt3>
                            <Q4PreviewDownloadCod>
                              {`4. Preview & Download code`}
                            </Q4PreviewDownloadCod>
                            <Subtxt4>
                              <PreviewTheComponentU>
                                {`Preview the component using the Preview button. Download the ReactJS component code and view it in your code editor.`}
                              </PreviewTheComponentU>
                            </Subtxt4>
                          </Txt3>
                        </Content4>
                      </OnboardingRow3>
                    </Checklist1>
                  </Checklist>
                </QuickStart>
              </LeftSide>
              <RightSide>
                {false && (
                  <Step1Imagery
                    src={Step1ImageryImage}
                    loading="lazy"
                    alt={'Step1_imagery'}
                  />
                )}
                {false && (
                  <Step2Imagery
                    src={Step2ImageryImage}
                    loading="lazy"
                    alt={'Step2_imagery'}
                  />
                )}
                {false && (
                  <Step3Imagery
                    src={Step3ImageryImage}
                    loading="lazy"
                    alt={'Step3_imagery'}
                  />
                )}
                <Step4Imagery
                  src={Step4ImageryImage}
                  loading="lazy"
                  alt={'Step4_imagery'}
                />
              </RightSide>
            </Content>
          </Steps1>
        </Steps>
      )}
      {false && (
        <Resources>
          {false && (
            <Banner1>
              <Row1>
                <ThanksTxt1>
                  <Thanks1>{`Thanks!`}</Thanks1>
                  <YourAccountIsNowSetu1>
                    {`Your Account is now setup with Next.js as the export type & Typescript as the file type. `}
                  </YourAccountIsNowSetu1>
                </ThanksTxt1>
                <XOut1 src={XOut1Image} loading="lazy" alt={'X out'} />
              </Row1>
            </Banner1>
          )}
          <Thanks2>
            <Top2>
              <Avatar3>
                <A1>{`A`}</A1>
              </Avatar3>
              <Name1>
                <Andrew1>{`Andrew`}</Andrew1>
              </Name1>
              <ButtonText1 variant="text" size="medium" color="primary">
                {' '}
                Edit Profile{' '}
              </ButtonText1>
            </Top2>
            <ResourceBoxes>
              {false && (
                <Title>
                  <IconAndTitle>
                    <Resources1>{`Resources`}</Resources1>
                  </IconAndTitle>
                </Title>
              )}
              <Row2>
                <Resource>
                  <Top3>
                    <IconAndTitle1>
                      <DashIconMui
                        src={DashIconMuiImage}
                        loading="lazy"
                        alt={'dash_icon_MUI'}
                      />
                    </IconAndTitle1>
                    <Description>
                      <OverviewVideo>{`Overview Video`}</OverviewVideo>
                    </Description>
                  </Top3>
                </Resource>
                <Resource1>
                  <Top4>
                    <IconAndTitle2>
                      <IconDashReact
                        src={IconDashReactImage}
                        loading="lazy"
                        alt={'icon_dash_react'}
                      />
                    </IconAndTitle2>
                    <Description1>
                      <QuickStartDoc>{`Quick Start Doc`}</QuickStartDoc>
                    </Description1>
                  </Top4>
                </Resource1>
                <Resource2>
                  <Top5>
                    <IconAndTitle3>
                      <IconDashExport
                        src={IconDashExportImage}
                        loading="lazy"
                        alt={'icon_dash_export'}
                      />
                    </IconAndTitle3>
                    <Description2>
                      <GetTheFigmaPlugin>
                        {`Get the Figma Plugin`}
                      </GetTheFigmaPlugin>
                    </Description2>
                  </Top5>
                </Resource2>
                <Resource3>
                  <Top6>
                    <IconAndTitle4>
                      <IconDashZoom
                        src={IconDashZoomImage}
                        loading="lazy"
                        alt={'icon_dash_zoom'}
                      />
                    </IconAndTitle4>
                    <Description3>
                      <JoinUsOnDiscord>{`Join Us on Discord`}</JoinUsOnDiscord>
                    </Description3>
                  </Top6>
                </Resource3>
                <Resource4>
                  <Top7>
                    <IconAndTitle5>
                      <IconDashZoom1
                        src={IconDashZoom1Image}
                        loading="lazy"
                        alt={'icon_dash_zoom'}
                      />
                    </IconAndTitle5>
                    <Description4>
                      <ScheduleDemoOnboardi>
                        {`Schedule Demo/Onboarding`}
                      </ScheduleDemoOnboardi>
                    </Description4>
                  </Top7>
                </Resource4>
              </Row2>
              <Links>
                <IconAndTitle6>
                  <Links1>{`Links`}</Links1>
                  <Link3 href="#" underline="hover">
                    Quest Docs
                  </Link3>
                  <Link4 href="#" underline="hover">
                    Duplicate the Free MUI Kit
                  </Link4>
                  <Link5 href="#" underline="hover">
                    Get the Full MUI Kit
                  </Link5>
                  <Link6 href="#" underline="hover">
                    Component Samples & Templates
                  </Link6>
                  <Link7 href="#" underline="hover">
                    Revisit Quick Start Guide
                  </Link7>
                </IconAndTitle6>
              </Links>
            </ResourceBoxes>
          </Thanks2>
          <Resources2></Resources2>
        </Resources>
      )}
    </Dashboard1>
  );
}

export default Dashboard;
