/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

const useResources = (props) => {
  let data = {};
  const handleLinkClick = (param1) => {};
  const handleOnHoverEnter = (param1, param2) => {};
  const handleOnHoverLeave = (param1, param2) => {};

  let fns = { handleLinkClick, handleOnHoverEnter, handleOnHoverLeave };
  return { data, fns };
};

export default useResources;
